export const PAGE_SIZE = 10;

export const emptyConsignmentForm = {
  viewMode: 'GST',
  gstType: '',
  gstNo: '',
  imsNo: '',
  serialNo: '',
  ledgerDate: '',
  loadingDate: '',
  deliveryDateTime: '',
  customerName: '',
  billTo: '',
  truckNo: '',
  truckType: '',
  ownerName: '',
  ownerPrimaryContact: '',
  ownerAlternateContact: '',
  driverName: '',
  dlNo: '',
  driverPrimaryContact: '',
  driverAlternateContact: '',
  fromLocation: '',
  toLocation: '',
  material: '',
  netWeight: '',
  tareWeight: '',
  actualWeight: '',
  grossWeight: '',
  weightUnit: 'MT',
  supplierRateType: 'fixed_cost',
  supplierAmount: '',
  chargeableWeight: '',
  haltingCharge: '',
  parkingCharge: '',
  commission: '',
  netBalance: '',
  advance: '',
  advanceEntries: [{ id: 1, amount: '', refNo: '' }],
  totalAdvance: '',
  balance: '',
  ledgerAmount: '',
  profitFixedCost: '',
  profitCostPerMT: '',
  profitChargeableWeight: '',
  customerRate: '',
  additionalCharges: '',
  otherExpenses: '',
  expenses: '',
  gstAmount: '',
  netFreight: '',
  profit: '',
  lrNo: '',
  lrDate: '',
  invoiceNo: '',
  invoiceDate: '',
  paymentStatus: '',
  paymentMode: '',
  truckpaymentMode: '',
  customerPaymentMode: '',
  paymentType: '',
  remarks: '',
  additionalFiles: [],
};

export const truckTypeOptions = ['32 ft SXL', 'Mini', '17ft', '20ft', 'Trailer'];
export const paymentStatusOptions = ['Advance 1', 'Advance 2', 'Advance 3'];
export const paymentModeOptions = ['Bank Transfer', 'DD', 'Cheque', 'UPI', 'Cash'];
export const supplierRateTypeOptions = [
  { label: 'Fixed Cost', value: 'fixed_cost' },
  { label: 'Cost Per MT', value: 'cost_per_mt' },
];
export const PaymentTypeOptions = [
  { label: 'Driver Payment', value: 'Driver_Payment' },
  { label: 'Truck Owner', value: 'Truck_Owner' },
];
export const numericConsignmentFields = new Set([
  'netWeight',
  'tareWeight',
  'actualWeight',
  'grossWeight',
  'supplierAmount',
  'chargeableWeight',
  'chargebleWeight',
  'haltingCharge',
  'parkingCharge',
  'commission',
  'netBalance',
  'advance',
  'totalAdvance',
  'balance',
  'ledgerAmount',
  'profitFixedCost',
  'profitCostPerMT',
  'profitChargeableWeight',
  'customerRate',
  'additionalCharges',
  'otherExpenses',
  'expenses',
  'gstAmount',
  'netFreight',
  'profit',
]);
