export const PAGE_SIZE = 10;

export const emptyConsignmentForm = {
  viewMode: 'GST',
  gstType: '',
  gstNo: '',
  imsNo: '',
  serialNo: '',
  ledgerDate: '',
  loadingDate: '',
  deliveryDateTime: '',
  customerName: '',
  billTo: '',
  truckNo: '',
  truckType: '',
  ownerName: '',
  ownerPrimaryContact: '',
  ownerPrimaryWhatsappAvailable: false,
  ownerAlternateContact: '',
  ownerAlternateWhatsappAvailable: false,
  driverName: '',
  driverPrimaryContact: '',
  driverPrimaryWhatsappAvailable: false,
  driverAlternateContact: '',
  driverAlternateWhatsappAvailable: false,
  fromLocation: '',
  toLocation: '',
  netWeight: '',
  tareWeight: '',
  actualWeight: '',
  crossVehicleWeight: '',
  weight: '',
  supplierAmount: '',
  advance: '',
  balance: '',
  ledgerAmount: '',
  customerRate: '',
  additionalCharges: '',
  expenses: '',
  netFreight: '',
  profit: '',
  lrNo: '',
  lrDate: '',
  invoiceNo: '',
  invoiceDate: '',
  paymentStatus: '',
  paymentMode: '',
  remarks: '',
};

export const truckTypeOptions = ['32 ft SXL', 'Mini', '17ft', '20ft', 'Trailer'];
export const paymentStatusOptions = ['Advance 1', 'Advance 2', 'Advance 3'];
export const paymentModeOptions = ['Bank Transfer', 'DD', 'Cheque', 'UPI', 'Cash'];
export const numericConsignmentFields = new Set([
  'netWeight',
  'tareWeight',
  'actualWeight',
  'crossVehicleWeight',
  'weight',
  'supplierAmount',
  'advance',
  'balance',
  'ledgerAmount',
  'customerRate',
  'additionalCharges',
  'expenses',
  'netFreight',
  'profit',
]);
